[package]
name = "path-intellisense-lsp"
version = "0.0.1"
edition = "2024"
publish = false
license-file = "LICENSE"
repository = "https://github.com/MengLinMaker/path-intellisense-lsp"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
